# Generated by Django 4.2.5 on 2023-09-26 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultad', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Grupodeinvestigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupoinvestigacion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Rol_investigador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolinvestifador', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Semilleroinvestigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semilleroinvestigacion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tipoestudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolinvestifador', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.CharField(max_length=150)),
                ('identificacion', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('telefono', models.CharField(max_length=20)),
                ('programa', models.CharField(max_length=150)),
                ('semestre', models.IntegerField()),
                ('facultadid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.facultad')),
                ('grupoinvestigacionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.grupodeinvestigacion')),
                ('rolinvestigadorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol_investigador')),
                ('semilleroinvestigacionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.semilleroinvestigacion')),
                ('tipoestudianteid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.tipoestudiante')),
            ],
        ),
    ]
