# Generated by Django 4.2.5 on 2023-09-26 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol_investigador',
            old_name='rolinvestifador',
            new_name='rolinvestigador',
        ),
        migrations.RenameField(
            model_name='tipoestudiante',
            old_name='rolinvestifador',
            new_name='tipoestudiante',
        ),
    ]
