# Generated by Django 4.2.5 on 2023-09-27 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_remove_proyecto_usuarioid_delete_proyectoxusuario'),
        ('usuarios', '0002_rename_rolinvestifador_rol_investigador_rolinvestigador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='rolinvestigadorid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol_investigador'),
        ),
        migrations.CreateModel(
            name='ProyectoxUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyectoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
                ('usuariosid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='usuarios',
            name='proyectoid',
            field=models.ManyToManyField(through='usuarios.ProyectoxUsuario', to='proyectos.proyecto'),
        ),
    ]
