# Generated by Django 4.2.5 on 2023-09-27 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuarios_rolinvestigadorid_proyectoxusuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='estudiante',
            new_name='usuario',
        ),
    ]
