# Generated by Django 4.2.5 on 2023-09-27 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuarios_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='tipoestudianteid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.tipoestudiante'),
        ),
    ]
