# Generated by Django 4.2.5 on 2023-10-10 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_alter_archivo_archivo'),
        ('usuarios', '0006_alter_usuarios_tipoestudianteid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='grupoinvestigacionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.grupoinvestigacion'),
        ),
    ]
