# Generated by Django 4.2.5 on 2023-10-10 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuarios_grupoinvestigacionid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grupodeinvestigacion',
        ),
    ]
