# Generated by Django 4.2.5 on 2023-09-26 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convocatoria', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EntidadFinanciadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidadfinanciadora', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Grupoinvestigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupoinvestigacion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(max_length=150)),
                ('codigo', models.CharField(default='N/A', max_length=150, null=True)),
                ('plazo', models.IntegerField(default=0)),
                ('operador', models.CharField(max_length=50)),
                ('fechai', models.DateField()),
                ('fechaf', models.DateField()),
                ('convocatoriaid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.convocatoria')),
                ('entidadfinanciadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.entidadfinanciadora')),
                ('grupoinvestigacionid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.grupoinvestigacion')),
                ('operadorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.operador')),
            ],
        ),
        migrations.CreateModel(
            name='Rol_universidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolU', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tipoarchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoxUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyectoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
                ('usuariosid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='roluniversidadid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.rol_universidad'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='usuarioid',
            field=models.ManyToManyField(through='proyectos.ProyectoxUsuario', to='usuarios.usuarios'),
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='')),
                ('nombre_archivo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.tipoarchivo')),
                ('proyectoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
            ],
        ),
    ]
