# Generated by Django 4.2.5 on 2023-09-27 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='usuarioid',
        ),
        migrations.DeleteModel(
            name='ProyectoxUsuario',
        ),
    ]
