# Generated by Django 4.2.5 on 2023-09-27 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_remove_proyecto_usuarioid_delete_proyectoxusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='operador',
        ),
    ]
