# Generated by Django 4.2.5 on 2023-10-09 15:31

import apps.proyectos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_remove_proyecto_operador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(upload_to=apps.proyectos.models.archivo_upload_path),
        ),
    ]
