# Generated by Django 4.2.5 on 2023-10-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_alter_archivo_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fechaf',
            field=models.DateField(blank=True, null=True),
        ),
    ]
