# Generated by Django 4.2.5 on 2023-09-26 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Pasos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tipodependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipodependencia', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Seguimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripciontarea', models.CharField(max_length=150)),
                ('duracion', models.IntegerField()),
                ('tareadependencia', models.CharField(max_length=40)),
                ('diasdependencia', models.IntegerField()),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('responsable', models.CharField(max_length=40)),
                ('fechafin', models.DateField()),
                ('pasosid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimientos.pasos')),
                ('proyectoid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
                ('tarea_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguimientos.seguimientos')),
            ],
        ),
    ]
