# Generated by Django 4.2.5 on 2023-09-26 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientos',
            name='estadoid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguimientos.estado'),
        ),
    ]
