# Generated by Django 4.2.5 on 2023-09-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0003_seguimientos_tipodependenciaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientos',
            name='tareadependencia',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
