# Generated by Django 4.2.5 on 2023-10-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0005_remove_seguimientos_tareadependencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientos',
            name='diasdependencia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
