# Generated by Django 4.2.5 on 2023-10-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0006_alter_seguimientos_diasdependencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimientos',
            name='fin',
        ),
    ]
