# Generated by Django 4.2.5 on 2023-10-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0008_seguimientos_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientos',
            name='fechafin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
